# Generated by Django 3.2.8 on 2021-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(verbose_name='이름'),
        ),
    ]
