# Generated by Django 3.2.8 on 2021-12-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movienote_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienote',
            name='movieNm',
            field=models.TextField(max_length=128, verbose_name='movieNmEn'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='movieNm',
            field=models.TextField(max_length=128, verbose_name='movieNmEn'),
        ),
    ]
