# Generated by Django 3.2.8 on 2021-12-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211210_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienote',
            name='star',
            field=models.IntegerField(verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='star',
            field=models.IntegerField(verbose_name='별점'),
        ),
    ]
