# Generated by Django 3.2.8 on 2021-12-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211210_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienote',
            name='review',
            field=models.TextField(max_length=1024, verbose_name='리뷰'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='review',
            field=models.TextField(max_length=1024, verbose_name='리뷰'),
        ),
    ]
