# Generated by Django 3.2.8 on 2021-12-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211210_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='email',
            new_name='username',
        ),
    ]
