# Generated by Django 3.2.8 on 2021-12-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_notice_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='username',
            field=models.CharField(max_length=128, verbose_name='작성자'),
        ),
    ]
